import React, { useState } from 'react';
import { 
  Headphones, 
  MessageSquare, 
  Bell, 
  Volume2, 
  MessageCircle, 
  Search, 
  ChevronRight, 
  ChevronDown, 
  Copy, 
  Check, 
  ExternalLink,
  ShieldCheck,
  Smartphone,
  CreditCard,
  Lock,
  ArrowLeft
} from 'lucide-react';
import { soundService } from '../../services/sound';

interface SupportTabProps {
  onBack?: () => void;
  onOpenLiveChat?: () => void;
  language: 'en' | 'ur' | 'hi';
}

type SupportSubTab = 'support' | 'news' | 'notice' | 'marquee' | 'feedback';

interface FAQItem {
  id: string;
  category: 'app' | 'deposit' | 'withdraw' | 'security';
  question: string;
  answer: string;
}

const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'app',
    question: '1. How to download the P999 official APP?',
    answer: 'Click the "Download APP" banner at the top of the homepage or visit https://111p999.com/apk. After downloading the APK package, enable "Install Unknown Apps" in your Android settings and install it to receive an exclusive Rs 999 download bonus!',
  },
  {
    id: 'faq-2',
    category: 'deposit',
    question: '2. How to deposit using JazzCash and EasyPaisa?',
    answer: 'Navigate to the Deposit tab, select JazzCash or EasyPaisa (+5% bonus), enter your deposit amount (min Rs 100), copy our official merchant wallet number, transfer via your mobile wallet app, and paste the 12-digit Transaction ID (TID) to get instant credit in 15 seconds.',
  },
  {
    id: 'faq-3',
    category: 'withdraw',
    question: '3. What is the withdrawal speed and minimum limit?',
    answer: 'The minimum withdrawal is Rs 300. Withdrawals to JazzCash, EasyPaisa, or Pakistani Local Banks are processed automatically 24/7, usually arriving within 3 to 10 minutes without any handling fee.',
  },
  {
    id: 'faq-4',
    category: 'security',
    question: '4. How does the 3.0% agent commission and referral work?',
    answer: 'Share your exclusive invitation link (e.g. ?dl=193623200). You earn up to 3.0% commission daily on all betting turnover generated by your direct players and team members, settled automatically every day!',
  },
  {
    id: 'faq-5',
    category: 'security',
    question: '5. What should I do if my account login is restricted?',
    answer: 'Please contact our 24/7 online customer service via WhatsApp or Live Chat with your registered mobile number and ID 193623200. Our risk management team will verify and unlock your account immediately.',
  },
];

export const SupportTab: React.FC<SupportTabProps> = ({ onBack, onOpenLiveChat, language }) => {
  const [activeTab, setActiveTab] = useState<SupportSubTab>('support');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedFaqCat, setSelectedFaqCat] = useState<'all' | 'app' | 'deposit' | 'withdraw' | 'security'>('all');
  const [openFaqId, setOpenFaqId] = useState<string | null>('faq-1');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  
  // Feedback form state
  const [feedbackType, setFeedbackType] = useState('Game Experience');
  const [feedbackText, setFeedbackText] = useState('');
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);

  const handleCopy = (text: string, key: string) => {
    soundService.playClick();
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const filteredFaqs = FAQS.filter((f) => {
    const matchCat = selectedFaqCat === 'all' || f.category === selectedFaqCat;
    const matchSearch = searchQuery.trim() === '' || 
      f.question.toLowerCase().includes(searchQuery.toLowerCase()) || 
      f.answer.toLowerCase().includes(searchQuery.toLowerCase());
    return matchCat && matchSearch;
  });

  return (
    <div className="space-y-3 pb-24 max-w-2xl mx-auto text-slate-100">
      {/* Header Bar */}
      <div className="flex items-center justify-between bg-[#081524] border-b border-slate-800 px-3 py-2.5 rounded-2xl shadow-md">
        <div className="flex items-center gap-2">
          {onBack && (
            <button
              onClick={onBack}
              className="p-1 rounded-lg text-slate-400 hover:text-white transition cursor-pointer"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
          )}
          <h2 className="text-base font-bold text-white tracking-wide">Message Center</h2>
        </div>
        <div className="flex items-center gap-1.5 text-xs text-emerald-400 font-medium">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
          <span>Online 24/7</span>
        </div>
      </div>

      {/* Tabs Header */}
      <div className="flex items-center justify-between border-b border-slate-800/80 bg-[#0a1728] rounded-xl px-1 py-1">
        {[
          { id: 'support' as SupportSubTab, label: 'Support', icon: Headphones },
          { id: 'news' as SupportSubTab, label: 'News', badge: '1', icon: Bell },
          { id: 'notice' as SupportSubTab, label: 'Notice', icon: MessageSquare },
          { id: 'marquee' as SupportSubTab, label: 'Marquee', icon: Volume2 },
          { id: 'feedback' as SupportSubTab, label: 'Reward Feedback', icon: MessageCircle },
        ].map((tab) => {
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => {
                soundService.playClick();
                setActiveTab(tab.id);
              }}
              className={`relative flex-1 py-2 px-1 text-center text-xs font-bold transition-all cursor-pointer whitespace-nowrap ${
                isActive
                  ? 'text-amber-400 font-black border-b-2 border-amber-400'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <span>{tab.label}</span>
              {tab.badge && (
                <span className="ml-1 px-1.5 py-0.2 rounded-full text-[9px] bg-rose-600 text-white font-bold">
                  {tab.badge}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {/* TAB 1: Support */}
      {activeTab === 'support' && (
        <div className="space-y-3">
          {/* 24/7 Customer Service Card */}
          <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-3.5 shadow-lg space-y-2.5">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-emerald-500/20 text-emerald-400">
                <Headphones className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-white">24/7 Customer Service</h3>
                <p className="text-[11px] text-slate-400">
                  Chat with the professional customer service online to solve your problems.
                </p>
              </div>
            </div>

            {/* Support Channels Grid */}
            <div className="grid grid-cols-4 gap-1.5 pt-1">
              <button
                onClick={() => {
                  soundService.playClick();
                  if (onOpenLiveChat) onOpenLiveChat();
                }}
                className="flex flex-col items-center justify-center p-2 rounded-xl bg-[#10243e] hover:bg-[#163052] border border-slate-700/60 transition cursor-pointer"
              >
                <div className="w-8 h-8 rounded-full bg-amber-400 text-slate-950 flex items-center justify-center font-bold text-sm shadow">
                  🎧
                </div>
                <span className="text-[10px] font-bold text-slate-200 mt-1">Online CS</span>
              </button>

              <button
                onClick={() => {
                  soundService.playClick();
                  window.open('https://wa.me/923001234567', '_blank');
                }}
                className="flex flex-col items-center justify-center p-2 rounded-xl bg-[#10243e] hover:bg-[#163052] border border-slate-700/60 transition cursor-pointer"
              >
                <div className="w-8 h-8 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-sm shadow">
                  📱
                </div>
                <span className="text-[10px] font-bold text-slate-200 mt-1">WhatsApp</span>
              </button>

              <button
                onClick={() => {
                  soundService.playClick();
                  window.open('https://t.me/P999_Official', '_blank');
                }}
                className="flex flex-col items-center justify-center p-2 rounded-xl bg-[#10243e] hover:bg-[#163052] border border-slate-700/60 transition cursor-pointer"
              >
                <div className="w-8 h-8 rounded-full bg-sky-500 text-white flex items-center justify-center font-bold text-sm shadow">
                  ✈️
                </div>
                <span className="text-[10px] font-bold text-slate-200 mt-1">Telegram</span>
              </button>

              <button
                onClick={() => {
                  soundService.playClick();
                  window.open('https://facebook.com/P999Official', '_blank');
                }}
                className="flex flex-col items-center justify-center p-2 rounded-xl bg-[#10243e] hover:bg-[#163052] border border-slate-700/60 transition cursor-pointer"
              >
                <div className="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center font-bold text-sm shadow">
                  📘
                </div>
                <span className="text-[10px] font-bold text-slate-200 mt-1">Facebook</span>
              </button>
            </div>
          </div>

          {/* Official Channel List */}
          <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-3.5 shadow-lg space-y-2">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wide">
              Official Dedicated Channels
            </h4>

            {/* WhatsApp Item */}
            <div className="flex items-center justify-between p-2.5 rounded-xl bg-[#0e223d] border border-slate-700/50">
              <div className="flex items-center gap-2.5">
                <div className="w-9 h-9 rounded-full bg-emerald-600 flex items-center justify-center text-lg text-white shadow">
                  📞
                </div>
                <div>
                  <div className="text-xs font-bold text-white">Nickname: WhatsApp VIP Support</div>
                  <div className="text-[11px] text-slate-400 font-mono flex items-center gap-1">
                    <span>P999.pro | Official Channel</span>
                    <button
                      onClick={() => handleCopy('P999.pro Official WhatsApp', 'wa')}
                      className="text-amber-400 hover:text-amber-300"
                    >
                      {copiedKey === 'wa' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    </button>
                  </div>
                  <div className="text-[10px] text-emerald-400">Online time: 00:00 - 23:59</div>
                </div>
              </div>
              <button
                onClick={() => {
                  soundService.playClick();
                  window.open('https://wa.me/923001234567', '_blank');
                }}
                className="px-3 py-1.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs shadow transition cursor-pointer"
              >
                Contact Now
              </button>
            </div>

            {/* Telegram Item */}
            <div className="flex items-center justify-between p-2.5 rounded-xl bg-[#0e223d] border border-slate-700/50">
              <div className="flex items-center gap-2.5">
                <div className="w-9 h-9 rounded-full bg-sky-500 flex items-center justify-center text-lg text-white shadow">
                  ✈️
                </div>
                <div>
                  <div className="text-xs font-bold text-white">Nickname: Telegram Channel &amp; Bot</div>
                  <div className="text-[11px] text-slate-400 font-mono flex items-center gap-1">
                    <span>@P999_Official_Bot</span>
                    <button
                      onClick={() => handleCopy('@P999_Official_Bot', 'tg')}
                      className="text-amber-400 hover:text-amber-300"
                    >
                      {copiedKey === 'tg' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    </button>
                  </div>
                  <div className="text-[10px] text-emerald-400">Daily Free Redeem Codes Released</div>
                </div>
              </div>
              <button
                onClick={() => {
                  soundService.playClick();
                  window.open('https://t.me/P999_Official', '_blank');
                }}
                className="px-3 py-1.5 rounded-xl bg-sky-500 hover:bg-sky-400 text-white font-bold text-xs shadow transition cursor-pointer"
              >
                Join Channel
              </button>
            </div>
          </div>

          {/* Help Center Card & FAQ List */}
          <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-3.5 shadow-lg space-y-3">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wide">
              Help Center &amp; Self-Service
            </h4>

            {/* Search Input */}
            <div className="relative">
              <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Enter your question (e.g. Deposit, EasyPaisa, Bonus)..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-[#081524] border border-slate-700/80 rounded-xl pl-9 pr-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-400"
              />
            </div>

            {/* FAQ Pills */}
            <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none">
              {[
                { id: 'all', label: 'All FAQs' },
                { id: 'app', label: 'Download APP' },
                { id: 'deposit', label: 'Deposit Problem' },
                { id: 'withdraw', label: 'Withdrawal' },
                { id: 'security', label: 'Account Security' },
              ].map((pill) => (
                <button
                  key={pill.id}
                  onClick={() => {
                    soundService.playClick();
                    setSelectedFaqCat(pill.id as any);
                  }}
                  className={`px-2.5 py-1 rounded-lg text-xs font-bold whitespace-nowrap transition cursor-pointer ${
                    selectedFaqCat === pill.id
                      ? 'bg-amber-400 text-slate-950 font-black shadow'
                      : 'bg-[#10243e] text-slate-300 hover:text-white'
                  }`}
                >
                  {pill.label}
                </button>
              ))}
            </div>

            {/* Collapsible FAQ List */}
            <div className="space-y-1.5 pt-1">
              {filteredFaqs.map((faq) => {
                const isOpen = openFaqId === faq.id;
                return (
                  <div
                    key={faq.id}
                    className="rounded-xl bg-[#0e223d] border border-slate-700/50 overflow-hidden transition"
                  >
                    <button
                      onClick={() => {
                        soundService.playClick();
                        setOpenFaqId(isOpen ? null : faq.id);
                      }}
                      className="w-full p-2.5 text-left flex items-center justify-between text-xs font-bold text-slate-200 hover:text-amber-300 transition cursor-pointer"
                    >
                      <span>{faq.question}</span>
                      {isOpen ? (
                        <ChevronDown className="w-4 h-4 text-amber-400 shrink-0" />
                      ) : (
                        <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
                      )}
                    </button>
                    {isOpen && (
                      <div className="px-3 pb-3 text-xs text-slate-300 leading-relaxed border-t border-slate-700/40 pt-2 bg-[#081524]/60">
                        {faq.answer}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: News */}
      {activeTab === 'news' && (
        <div className="space-y-2.5">
          <div className="bg-[#0b1b30] border border-amber-500/30 rounded-2xl p-4 shadow-lg space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-black bg-amber-400/20 text-amber-300 border border-amber-400/30 px-2 py-0.5 rounded-full">
                NEW FEATURE &bull; 26/08/2026
              </span>
              <span className="text-[11px] text-slate-400">10:45 AM</span>
            </div>
            <h3 className="text-sm font-bold text-white">
              🎉 P999 Mysterious Red Envelope Daily Draw is Live!
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              Every day at 12:00 PM and 8:00 PM PKT, active members who recharge Rs 100 or more will automatically receive lucky mystery red envelopes up to Rs 100,000! Check your Reward Center to claim.
            </p>
          </div>

          <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-4 shadow-lg space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 px-2 py-0.5 rounded-full">
                PAYMENT UPDATE
              </span>
              <span className="text-[11px] text-slate-400">25/08/2026</span>
            </div>
            <h3 className="text-sm font-bold text-white">
              ⚡ Instant 15-Second Deposit Channel Upgraded
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              EasyPaisa and JazzCash automated deposit speed has been enhanced. All recharge transactions now include an instant +5% cashback bonus directly added to your balance.
            </p>
          </div>
        </div>
      )}

      {/* TAB 3: Notice */}
      {activeTab === 'notice' && (
        <div className="space-y-2.5">
          <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-4 shadow-lg space-y-2">
            <h3 className="text-sm font-bold text-amber-300 flex items-center gap-1.5">
              <span>⚠️ Official Anti-Fraud &amp; Domain Verification</span>
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              Please strictly recognize our official domains <strong className="text-amber-300">P999.ONE</strong> and <strong className="text-amber-300">111p999.com</strong>. P999 customer representatives will never ask for your password, OTP, or withdrawal PIN.
            </p>
          </div>

          <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-4 shadow-lg space-y-2">
            <h3 className="text-sm font-bold text-white">
              🛡️ Account Security Guidelines
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed">
              To guarantee the security of your funds, please bind your real mobile number and set up a 6-digit withdrawal security password in the Security Center.
            </p>
          </div>
        </div>
      )}

      {/* TAB 4: Marquee */}
      {activeTab === 'marquee' && (
        <div className="space-y-2.5">
          <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-4 shadow-lg space-y-3">
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wide">
              Recent System Broadcasts
            </h3>
            <div className="space-y-2 text-xs text-slate-300">
              <div className="p-2.5 rounded-xl bg-[#081524] border border-slate-800">
                <span className="text-amber-400 font-bold">📢 [System Notice]:</span> P999 official website 【P999.ONE】 Collection ~ Must bookmark! Daily lucky envelope draw up to Rs 100,000!
              </div>
              <div className="p-2.5 rounded-xl bg-[#081524] border border-slate-800">
                <span className="text-emerald-400 font-bold">📢 [Winner]:</span> Congratulations to player 3***89 for winning Rs 45,000 on Super Ace 777!
              </div>
              <div className="p-2.5 rounded-xl bg-[#081524] border border-slate-800">
                <span className="text-sky-400 font-bold">📢 [Agent]:</span> Agent ID 40****416 earned Rs 64,695.41 in daily commission today!
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 5: Reward Feedback */}
      {activeTab === 'feedback' && (
        <div className="bg-[#0b1b30] border border-slate-700/60 rounded-2xl p-4 shadow-lg space-y-3">
          <h3 className="text-sm font-bold text-white flex items-center gap-1.5">
            <span>🎁 Submit Suggestions &amp; Win Bonus Cash</span>
          </h3>
          <p className="text-xs text-slate-300">
            Submit valuable bug reports or feedback. Once adopted by our engineers, you will receive a bonus of Rs 100 to Rs 5,000!
          </p>

          {feedbackSubmitted ? (
            <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-center space-y-1">
              <span className="text-2xl">🎉</span>
              <h4 className="text-xs font-bold text-emerald-400">Feedback Submitted Successfully!</h4>
              <p className="text-[11px] text-slate-300">Our customer team will review your feedback within 24 hours.</p>
              <button
                onClick={() => {
                  setFeedbackSubmitted(false);
                  setFeedbackText('');
                }}
                className="mt-2 text-xs text-amber-300 font-bold underline cursor-pointer"
              >
                Submit another feedback
              </button>
            </div>
          ) : (
            <div className="space-y-2.5">
              <div>
                <label className="text-[11px] font-bold text-slate-300 block mb-1">Feedback Category</label>
                <select
                  value={feedbackType}
                  onChange={(e) => setFeedbackType(e.target.value)}
                  className="w-full bg-[#081524] border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-amber-400"
                >
                  <option>Game Experience &amp; Odds</option>
                  <option>Deposit &amp; EasyPaisa / JazzCash</option>
                  <option>Withdrawal Processing Speed</option>
                  <option>Invitation &amp; Commission Settlement</option>
                  <option>Bug Report / Other</option>
                </select>
              </div>

              <div>
                <label className="text-[11px] font-bold text-slate-300 block mb-1">Feedback Description</label>
                <textarea
                  rows={3}
                  value={feedbackText}
                  onChange={(e) => setFeedbackText(e.target.value)}
                  placeholder="Please describe your issue or suggestion in detail..."
                  className="w-full bg-[#081524] border border-slate-700 rounded-xl p-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-400"
                />
              </div>

              <button
                onClick={() => {
                  if (!feedbackText.trim()) {
                    alert('Please enter your feedback text');
                    return;
                  }
                  soundService.playWin();
                  setFeedbackSubmitted(true);
                }}
                className="w-full py-2.5 rounded-xl bg-gradient-to-r from-amber-400 to-yellow-400 text-slate-950 font-bold text-xs shadow-md hover:from-amber-300 hover:to-yellow-300 transition cursor-pointer"
              >
                Submit Feedback
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
